- name: 'pkg.dev/cloud-builders/gcloud'
  args: ['builds', 'submit', '--region=us-central1', '--tag', 'us-central1-docker.pkg.dev/projetorodrigo-381505/front-end/$REVISION_ID', './']

- name: "pkg.dev/cloud-builders/gcloud"
  args: ["run", "deploy", "front-end", "--image", "us-central1-docker.pkg.dev/projetorodrigo-381505/front-end/$REVISION_ID", "--max-instances=1", "--ingress=all", "--region", "us-central1", "--allow-unauthenticated"]
